import pandas as pd
from typing import List, Optional, Iterable, Union, Callable
import numpy as np

"""
A mutable **abstract** class that performs a Kalman filter, implementation based on 
https://thekalmanfilter.com/kalman-filter-explained-simply/.
Subclasses need to overwrite :py:func'initialize_parameters'
"""
class Kalman:
    
    """
    Initialization method for the Kalman class.
    :param inputs: dataset to be smoothed out by the Kalman filter with an expected form 
        of `endaq.ide.to_pandas`. All parameters in the dataset will be assumed to be used.

    :param A: the initial state transition matrix, 
        determned by the subclass that implements this.
    :param H: the initial state to measurement matrix, 
        determned by the subclass that implements this. 
    :param Q: the initial process noise covariance matrix, 
        determned by the subclass that implements this.
    :param name: the name of the row that will hold the data generated by the kalman filter. 
        Set to "filtered data" by default.
    """    
    def __init__(
        self,
        inputs: pd.DataFrame,
        A: np.array,
        H: Optional[np.array],
        Q: Optional[np.array],
        name: str = "filtered data",

       ):
        pre_init = len(inputs)
        X, P = self._init_update(inputs)
        if len(inputs) == pre_init:
            raise SubClassError(
                "subclass needs to remove the data points used in _init_update")
        self.Z = inputs
        self.A = A
        self.H = H
        self.Q = Q
        self.X = X

        self.P = P
        self.K = None
    
    #============= Optional Getters  =============#
    
    """
    Getter for the weight parameters.
    :return: a 3-tuple composed of the immutable copies of A, H, and Q, indexed respectively. 
    """
    def get_weights(self) -> tuple[np.array, np.array, np.array]:
        return (self.A, self.H, self.Q)

    """
    Getter for the Kalman Gain associated with this Object.
    :return: an immutable float representing the Kalman gain.
    """
    def get_gain(self) -> float:
        #by default, K is immutable
        return self.K    
    #============= Public Methods    =============#

    """
    Runs a Kalman filter on all steps for `inputs` set in :py:func:`__init__`.
    :return: a pandas `Series` object, with original timesteps and the computed values. 
        If insufficient enough data, the original Dataset will be returned instead.
    """
    def run(self) -> Union[pd.Series | pd.DataFrame]:
        np_df = self.input.to_numpy()
        if len(np_df <= 1):
            return self.input
        if not self.P:
            self.initialize_parameters()
        for z in np_df:
            self._update_weights(z)
        
    """
    Predicts the filtered value generated by the Kalman filter at the given point.
    :param z: the measurement vector to predict on.
    """
    def predict(self, z: np.array) -> np.array:

        raise NotImplementedError()

    """
    helper method for :py:func:`__init__`. Performs the first two steps 
    of the Kalman filter.
    :return: a tuple containing X_n and P_n, index respective
    """
    def initialize_parameters(self) -> tuple[np.array, np.array]:
        raise SubClassError("subclasses need to implement this method")

    #=============   Helper Methods  =============#


    """
    Helper method for :py:func:`run`. Updates the internal weights used by the Kalman filter.
    :param z: the current measurement value
    :return: None. The method mutates data internal to the Kalman class.
    """
    def _update_weights(self, z) -> None:
        xp = np.matmul(self.A, self.x)
        pp = np.matmul(np.matmul(), np.transpose(self.A)) + self.Q
        ppht = np.matmul(pp, np.transpose(self.H))
        self.K = np.matmul(ppht, np.invert(np.matmul(self.H, ppht) + self.R))
        self.X = xp + np.matmul(self.K, np.matmul(z, np.matmul(self.H, xp)))
        self.P = pp - np.matmul(np.matmul(self.K, self.H), pp)


class SubClassError(Exception):
    pass