"""
Functions for retrieving summary data from a dataset.
"""
from collections import defaultdict
from datetime import timedelta

from idelib.dataset import Channel
import pandas as pd

from .measurement import ANY, MeasurementType, get_channels


def get_channel_table(dataset, measurement_type=ANY, **kwargs):
    """ Get summary data for all `SubChannel` objects in a `Dataset` that
        contain one or more type of sensor data.

        :param channels: A list of channels/subchannels to filter.
        :param measurement_type: A `MeasurementType`, a measurement type 'key'
            string, or a string of multiple keys generated by adding and/or
            subtracting `MeasurementType` objects to filter the results. Any
            'subtracted' types will be excluded.
        :returns: A Pandas `DataFrame` of summary data.
    """
    # We don't support multiple sessions on current Slam Stick/enDAQ recorders,
    # but in the event we ever do, this allows one to be specified like so:
    #
    # :param session: A `Session` or session ID to retrieve from a
    #     multi-session recording.
    session = kwargs.get('session', None)
    if session:
        session = getattr(session, 'sessionId', session)

    if hasattr(dataset, 'getPlots'):
        sources = dataset.getPlots(sort=False)
    else:
        sources = dataset

    result = defaultdict(list)
    for source in sources:
        result['Channel ID'].append(source.parent.id)
        result['Subchannel ID'].append(source.id)
        result['name'].append(source.name)
        result['type'].append(source.units[0])
        result['units'].append(source.units[1])

        data = source.getSession(session)
        samples = len(data)
        if samples:
            start = data[0][0]
            end = data[-1][0]
            duration = timedelta(microseconds=end-start)
        else:
            start = end = duration = None
        result['start'].append(start)
        result['end'].append(end)
        result['duration'].append(duration)
        result['samples'].append(samples)
        result['rate'].append(samples / ((end - start) / 10**6))

    return pd.DataFrame(result)
